nav:
  - Home: ./index.md
  - 🇬🇧🇧🇷 O Pesadelo dos Pesadelos (The Mother Of All Nightmares): 001-the-mother-of-all-nightmares.md
  - 🇧🇷 O que devemos uns aos outros: 002-o-que-devemos-uns-ao-outros.md
